name: Release
on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: "checkout :: terraform module :: docker registry"
        uses: actions/checkout@v1
      - name: "install :: nodejs setup"
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: "install :: release dependencies"
        run: |
          npm install @semantic-release/commit-analyzer
          npm install @semantic-release/release-notes-generator
          npm install @semantic-release/github
          npm install @semantic-release/exec
      - name: "release :: tag repo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release